# Generated by Django 5.2.6 on 2025-09-30 07:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='หมายเลขคำสั่งซื้อ')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการชำระเงิน'), ('PAID', 'ชำระเงินแล้ว'), ('SHIPPED', 'กำลังจัดส่ง'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะคำสั่งซื้อ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมสินค้า (ก่อนส่วนลด)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='มูลค่าส่วนลด')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดชำระสุทธิ')),
                ('full_name', models.CharField(max_length=255, verbose_name='ชื่อ-นามสกุล ผู้รับ')),
                ('email', models.EmailField(max_length=255, verbose_name='อีเมลติดต่อ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('shipping_address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('payment_method', models.CharField(choices=[('BANK', 'โอนเงินผ่านธนาคาร'), ('CREDIT', 'บัตรเครดิต/เดบิต'), ('COD', 'เก็บเงินปลายทาง')], default='BANK', max_length=10, verbose_name='ช่องทางการชำระเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('variant_size', models.CharField(max_length=100, verbose_name='ตัวเลือก/ขนาด')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product', verbose_name='สินค้าหลัก')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในคำสั่งซื้อ',
                'verbose_name_plural': 'รายการสินค้าในคำสั่งซื้อ',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('price_at_addition', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='ตะกร้า')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productvariant', verbose_name='ตัวเลือกสินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในตะกร้า',
                'verbose_name_plural': 'รายการสินค้าในตะกร้า',
                'unique_together': {('cart', 'variant')},
            },
        ),
    ]
