# Generated by Django 5.2.6 on 2025-10-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='สลิปหลักฐานการชำระเงิน'),
        ),
    ]
