# Generated by Django 5.2.6 on 2025-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to='payment_slips/%Y/%m/%d/', verbose_name='สลิปหลักฐานการโอนเงิน'),
        ),
    ]
