# Generated by Django 5.2.6 on 2025-09-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='คำอธิบายสินค้า')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('status', models.CharField(choices=[('DRAFT', 'ฉบับร่าง (Draft)'), ('PREORDER', 'เปิดรับ Pre-order'), ('ACTIVE', 'พร้อมจำหน่าย'), ('OUTOFSTOCK', 'สินค้าหมด')], default='DRAFT', max_length=10, verbose_name='สถานะสินค้า')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่าจะจัดส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='ตัวเลือก/ขนาด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ (Pre-order)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='สินค้าหลัก')),
            ],
            options={
                'verbose_name': 'ตัวเลือกสินค้า',
                'verbose_name_plural': 'ตัวเลือกสินค้า',
                'ordering': ['price'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
