# Generated by Django 5.2.6 on 2025-09-29 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อแบรนด์')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estimated_delivery_date',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='สินค้าแนะนำ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU หลัก'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาขายปัจจุบัน'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='ตัวเลือกหลัก'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาปกติ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='รายละเอียดสินค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='รูปภาพหลัก'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('PRE_ORDER', 'Pre-order'), ('DISCONTINUED', 'Discontinued')], default='AVAILABLE', max_length=20, verbose_name='สถานะสินค้า'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='สินค้า'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=50, verbose_name='ขนาด/ตัวเลือก'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนในสต็อก'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='แบรนด์'),
        ),
    ]
