# Generated by Django 5.2.6 on 2025-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='โค้ดโปรโมชั่น')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'เปอร์เซ็นต์ (%)'), ('FIXED', 'จำนวนเงินคงที่ (บาท)')], default='FIXED', max_length=10, verbose_name='ประเภทส่วนลด')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='มูลค่าส่วนลด')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='ยอดสั่งซื้อขั้นต่ำที่สามารถใช้โค้ดนี้ได้', max_digits=10, verbose_name='ยอดสั่งซื้อขั้นต่ำ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('valid_from', models.DateTimeField(verbose_name='ใช้ได้ตั้งแต่')),
                ('valid_to', models.DateTimeField(verbose_name='ใช้ได้ถึง')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่ใช้ได้สูงสุด')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่ถูกใช้ไป')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'โค้ดโปรโมชั่น',
                'verbose_name_plural': 'โค้ดโปรโมชั่น',
                'ordering': ['-valid_to'],
            },
        ),
    ]
